grpc_server:
  port: 50051 #port of the grpc server
graphql_server:
  port: 3000
database:
  username: token
  token: token
  path: ./secure-connect.zip
queue:
  uri: pulsar+ssl://pulsar-aws-eucentral1.streaming.datastax.com:6651
  topic_name: persistent://witty-cluster/default/products_topic
  token: some_token 